name: Cinema Booking Monitor

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  monitor:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Install Playwright Browsers
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Build project
        run: mvn clean compile

      - name: Run monitor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHAT_ID_2: ${{ secrets.CHAT_ID_2 }}
          BOOKING_URL: ${{ secrets.BOOKING_URL }}
        run: mvn exec:java -Dexec.mainClass=com.ahmed.monitor.Main
